;             
CREATE USER IF NOT EXISTS "" SALT '' HASH '' ADMIN;           
CREATE MEMORY TABLE PUBLIC.MENTIONS_0_1(
    DOC_BASE INT NOT NULL,
    DOC_ID INT NOT NULL,
    DOC_INDEX INT NOT NULL,
    LABEL VARCHAR(50) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    ID INT NOT NULL,
    PARENT_ID INT NOT NULL,
    CHILD_COUNT INT NOT NULL,
    CHILD_LABEL VARCHAR(50) NOT NULL,
    START_TOKEN INT NOT NULL,
    END_TOKEN INT NOT NULL
);          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MENTIONS_0_1;            
CREATE INDEX PUBLIC.MENTIONS_0_1_INDEX_MAIN ON PUBLIC.MENTIONS_0_1(DOC_BASE, DOC_ID, LABEL);  
CREATE INDEX PUBLIC.MENTIONS_0_1_INDEX_DOC_ID ON PUBLIC.MENTIONS_0_1(DOC_BASE, LABEL);        
