addSbtPlugin("com.typesafe.sbt" % "sbt-git" % "0.9.3")
addSbtPlugin("com.eed3si9n" % "sbt-buildinfo" % "0.9.0")
addSbtPlugin("com.jsuereth" % "sbt-pgp" % "2.0.0")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.8")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.12")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "0.14.10")
// REST API 
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.7.3")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker" % "1.5.0")
// https://github.com/sbt/sbt-native-packager
//addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.6.1")
// addSbtPlugin("com.typesafe.sbt" % "sbt-coffeescript" % "1.0.0")
// addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.0")
// addSbtPlugin("com.typesafe.sbt" % "sbt-jshint" % "1.0.4")
// addSbtPlugin("com.typesafe.sbt" % "sbt-rjs" % "1.0.8")
// addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.1")
// addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.1.0")
// addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.6")