name: Odinson CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # see https://github.com/actions/setup-java#testing-against-different-java-versions
      matrix:
        distribution: [ 'zulu', 'temurin' ]
        java: [ '8', '11' ]
    name: Java ${{ matrix.java }} (${{ matrix.distribution }})
    steps:
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Run tests
      run: sbt coverage test
    - name: Lint check via scalafmt
      if: ${{ (matrix.distribution == 'temurin') && (matrix.java == '8') }}
      run: sbt scalafmtCheckAll
    - name: Coverage Report
      if: ${{ (matrix.distribution == 'temurin') && (matrix.java == '8') }}
      run: sbt coverageReport
    - name: Upload coverage to Codecov
      if: ${{ (matrix.distribution == 'temurin') && (matrix.java == '8') }}
      uses: codecov/codecov-action@v1
