name: Odinson docker

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

# builds and publishes docker images for the default branch.
# images are tagged with short commit hash and latest.
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      ORG: "lumai"
    steps:
    # ensure we can log in to dockerhub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    # Setup docker
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # for multi-arch builds (ex. ARM 64)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2
    # JDK setup
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        distribution: "adopt"
        java-version: "11"
    # build
    - name: "test and build images"
      run: |
        sbt dockerize
    # publish
    - name: "Publish docker `lumai/odinson-extras` image"
      env:
        IMAGE_NAME: "odinson-extras"
      run: docker push --all-tags "${{ env.ORG }}/${IMAGE_NAME}"
    - name: "Publish docker `lumai/odinson-rest-api` image"
      env:
        ORG: "lumai"
        IMAGE_NAME: "odinson-rest-api"
      run: docker push --all-tags "${{ env.ORG }}/${IMAGE_NAME}"